version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PYTHONWARNINGS=ignore
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - postgres-db
    restart: unless-stopped
    user: root
    entrypoint: >
      sh -c "
      echo 'üîß –ù–∞—Å—Ç—Ä–æ–π–∫–∞ –ø—Ä–∞–≤ –¥–æ—Å—Ç—É–ø–∞ –¥–ª—è pgAdmin...' &&
      mkdir -p /var/lib/pgadmin/sessions &&
      mkdir -p /var/lib/pgadmin/storage &&
      chmod 777 /var/lib/pgadmin/sessions &&
      chmod 777 /var/lib/pgadmin/storage &&
      echo '‚úÖ –ü—Ä–∞–≤–∞ –Ω–∞—Å—Ç—Ä–æ–µ–Ω—ã, –∑–∞–ø—É—Å–∫ pgAdmin...' &&
      exec /entrypoint.sh
      "

  django:
    build: .
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    networks:
      - my-network
    depends_on:
      postgres-db:
        condition: service_healthy
    #tail -f /dev/null
    command: >
      sh -c "
      echo '–û–∂–∏–¥–∞–Ω–∏–µ PostgreSQL...' &&
      python wait_for_db.py &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

networks:
  my-network:
    driver: bridge
